version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - '3333:3333'
    env_file:
      - ./backend/.env.prod
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - '3000:80'
    depends_on:
      - backend
    restart: always
